//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChanArchiver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChanArchiver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgwhite {
            get {
                object obj = ResourceManager.GetObject("bgwhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;ChanARCHIVER&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/css/css.css&quot; /&gt;
        ///  &lt;/head&gt;
        ///
        ///  &lt;body&gt;
        ///    &lt;div id=&quot;top&quot;&gt;&lt;/div&gt;
        ///
        ///    &lt;br /&gt;
        ///
        ///    &lt;div class=&quot;desktop&quot;&gt;
        ///      &lt;a class=&quot;button&quot; href=&quot;/all.html&quot;&gt;Archived Threads Catalog&lt;/a&gt;
        ///      &lt;a class=&quot;button&quot; href=&quot;#bottom&quot;&gt;Bottom&lt;/a&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;hr /&gt;
        ///
        ///    &lt;div class=&quot;board&quot;&gt;
        ///      {DocumentBody}
        ///    &lt;/div&gt;
        ///
        ///    &lt;div class=&quot;desktop&quot;&gt;
        ///      &lt;a class=&quot;button&quot; href=&quot;/all.html&quot;&gt;Archived Threads Catal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string full_page {
            get {
                return ResourceManager.GetString("full_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hr {
            get {
                object obj = ResourceManager.GetObject("hr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;file&quot; id=&quot;f{file:id}&quot;&gt;
        ///    &lt;div class=&quot;fileInfo desktop&quot;&gt;
        ///        &lt;span class=&quot;fileText&quot; id=&quot;fT{file:id}&quot;&gt;
        ///        &lt;a class=&quot;fn&quot; href=&quot;{file:link}&quot;&gt;{file:name}&lt;/a&gt; - ({file:size}, {file:dimensions})&lt;/span&gt;
        ///    &lt;/div&gt;
        ///    &lt;a class=&quot;fileThumb&quot; href=&quot;{file:link}&quot; target=&quot;_blank&quot;&gt;
        ///        &lt;img src=&quot;{file:thumblink}&quot; alt=&quot;{file:name}&quot;/&gt;
        ///    &lt;/a&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string image_file {
            get {
                return ResourceManager.GetString("image_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html
        ///{
        ///    -webkit-text-size-adjust: 100%;
        ///}
        ///
        ///body
        ///{
        ///    margin-left: 0;
        ///    margin-right: 0;
        ///    margin-top: 5px;
        ///    padding-left: 15px;
        ///    padding-right: 15px;
        ///}
        ///
        ///.mobile, .mobileinline, .mobileib
        ///{
        ///    display: none !important;
        ///}
        ///
        ///div#footer
        ///{
        ///    clear: both;
        ///    text-align: center;
        ///}
        ///
        ///hr
        ///{
        ///    background: url(&quot;../res/hr.png&quot;) repeat-x scroll 0px 0px transparent;
        ///    border: 0px none;
        ///    color: rgb(204, 204, 204);
        ///    height: 4px;
        ///    padding: 0px;
        ///    clear: both;
        ///}        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layout {
            get {
                return ResourceManager.GetString("layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] locked {
            get {
                object obj = ResourceManager.GetObject("locked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;opContainer&quot; id=&quot;pc{wpost:id}&quot;&gt;
        ///  
        ///    &lt;div id=&quot;p{wpost:id}&quot; class=&quot;post op&quot;&gt;
        ///        {wpost:file}
        ///
        ///        &lt;div class=&quot;postInfo desktop&quot;&gt;
        ///            {wpost:subject}
        ///            &lt;span class=&quot;name&quot;&gt;{wpost:name}&lt;/span&gt;
        ///            {wpost:posterId}
        ///            &lt;span class=&quot;dateTime&quot;&gt;{wpost:time}&lt;/span&gt;
        ///
        ///            &lt;span class=&quot;postNum&quot;&gt;
        ///               &lt;a href=&quot;{postLink}&quot;&gt;No.&lt;/a&gt;
        ///
        ///               &lt;a href=&quot;#p{wpost:id}&quot; title=&quot;{wpost:id}&quot;&gt;{wpost:id}&lt;/a&gt;
        ///            &lt;/span&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string op_post {
            get {
                return ResourceManager.GetString("op_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;replyContainer&quot; id=&quot;pc{wpost:id}&quot;&gt;
        ///    
        ///    &lt;div id=&quot;p{wpost:id}&quot; class=&quot;post reply&quot;&gt;
        ///       
        ///        &lt;div class=&quot;postInfo desktop&quot;&gt;
        ///
        ///            {wpost:subject}
        ///            &lt;span class=&quot;name&quot;&gt;{wpost:name}&lt;/span&gt;
        ///            {wpost:posterId}
        ///            &lt;span class=&quot;dateTime&quot;&gt;{wpost:time}&lt;/span&gt;
        ///
        ///            &lt;span class=&quot;postNum&quot;&gt;
        ///                &lt;a href=&quot;#{wpost:id}&quot;&gt;No.&lt;/a&gt;
        ///                &lt;a href=&quot;#p{wpost:id}&quot; title=&quot;{wpost:id}&quot;&gt;{wpost:id}&lt;/a&gt;
        ///            &lt;/span&gt;
        ///
        ///        &lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reply_post {
            get {
                return ResourceManager.GetString("reply_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sticky {
            get {
                object obj = ResourceManager.GetObject("sticky", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;thread&quot; id=&quot;t{id}&quot;&gt;
        ///    {Content}
        ///&lt;/div&gt;&lt;hr /&gt;.
        /// </summary>
        internal static string thread {
            get {
                return ResourceManager.GetString("thread", resourceCulture);
            }
        }
    }
}
