//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChanArchiver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChanArchiver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _b {
            get {
                object obj = ResourceManager.GetObject("_b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - Archived Boards&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string archivedboard_page {
            get {
                return ResourceManager.GetString("archivedboard_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgwhite {
            get {
                object obj = ResourceManager.GetObject("bgwhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - Archived Boards&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string board_index_page {
            get {
                return ResourceManager.GetString("board_index_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/res/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - Monitored Boards&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string boards_page {
            get {
                return ResourceManager.GetString("boards_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.1.1 (http://getbootstrap.com)
        /// * Copyright 2011-2014 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///
        ////*! normalize.css v3.0.0 | MIT License | git.io/normalize */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_css {
            get {
                return ResourceManager.GetString("bootstrap_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.1.1 (http://getbootstrap.com)
        /// * Copyright 2011-2014 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;function b(){var a=document.createElement(&quot;bootstrap&quot;),b={WebkitTransition:&quot;webkitTransitionEnd&quot;,MozTransition:&quot;transitionend&quot;,OTransition:&quot;oTransitionEnd otransitionend&quot;,transition:&quot;transitionend&quot;};for(var c in b)if(void 0!==a.s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_js {
            get {
                return ResourceManager.GetString("bootstrap_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;boards&quot;: [{
        ///        &quot;board&quot;: &quot;3&quot;,
        ///        &quot;title&quot;: &quot;3DCG&quot;,
        ///        &quot;ws_board&quot;: 1,
        ///        &quot;per_page&quot;: 15,
        ///        &quot;pages&quot;: 11
        ///    }, {
        ///        &quot;board&quot;: &quot;a&quot;,
        ///        &quot;title&quot;: &quot;Anime \u0026 Manga&quot;,
        ///        &quot;ws_board&quot;: 1,
        ///        &quot;per_page&quot;: 15,
        ///        &quot;pages&quot;: 11
        ///    }, {
        ///        &quot;board&quot;: &quot;adv&quot;,
        ///        &quot;title&quot;: &quot;Advice&quot;,
        ///        &quot;ws_board&quot;: 1,
        ///        &quot;per_page&quot;: 15,
        ///        &quot;pages&quot;: 11
        ///    }, {
        ///        &quot;board&quot;: &quot;an&quot;,
        ///        &quot;title&quot;: &quot;Animals \u0026 Nature&quot;,
        ///        &quot;ws_board&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cached_boards {
            get {
                return ResourceManager.GetString("cached_boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Base structure
        /// */
        ///
        ////* Move down content because we have a fixed navbar that is 50px tall */
        ///body {
        ///  padding-top: 50px;
        ///}
        ///
        ///
        ////*
        /// * Global add-ons
        /// */
        ///
        ///.sub-header {
        ///  padding-bottom: 10px;
        ///  border-bottom: 1px solid #eee;
        ///}
        ///
        ///
        ////*
        /// * Sidebar
        /// */
        ///
        ////* Hide for mobile, show later */
        ///.sidebar {
        ///  display: none;
        ///}
        ///@media (min-width: 768px) {
        ///  .sidebar {
        ///    position: fixed;
        ///    top: 51px;
        ///    bottom: 0;
        ///    left: 0;
        ///    z-index: 1000;
        ///    display: block;
        ///    padding: 20px;
        ///    overflow-x: hidden;
        ///    overfl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dashboard_css {
            get {
                return ResourceManager.GetString("dashboard_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/res/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - Overview&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    &lt;lin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dashboard_page {
            get {
                return ResourceManager.GetString("dashboard_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///
        ///Holder - 2.3.1 - client side image placeholders
        ///(c) 2012-2014 Ivan Malopinsky / http://imsky.co
        ///
        ///Provided under the MIT License.
        ///Commercial use requires attribution.
        ///
        ///*/
        ///var Holder=Holder||{};!function(a,b){function c(a,b,c){b=parseInt(b,10),a=parseInt(a,10);var d=Math.max(b,a),e=Math.min(b,a),f=1/12,g=Math.min(.75*e,.75*d*f);return{height:Math.round(Math.max(c.size,g))}}function d(a){var b=[];for(p in a)a.hasOwnProperty(p)&amp;&amp;b.push(p+&quot;:&quot;+a[p]);return b.join(&quot;;&quot;)}function e(a){var b=a.ctx,d=a.dimensions [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string docs_js {
            get {
                return ResourceManager.GetString("docs_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] favicon_ico {
            get {
                object obj = ResourceManager.GetObject("favicon_ico", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/res/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - File Info&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    &lt;li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fileinfo {
            get {
                return ResourceManager.GetString("fileinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/res/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - File Queue&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    &lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string filequeue_page {
            get {
                return ResourceManager.GetString("filequeue_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/res/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - Thread Filters&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string filters_page {
            get {
                return ResourceManager.GetString("filters_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;&lt;/meta&gt;
        ///    &lt;title&gt;ChanArchiver&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/res/css.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/res/bootstrap.css&quot; /&gt;
        ///  &lt;/head&gt;
        ///
        ///  &lt;body&gt;
        ///    
        ///    &lt;div class=&quot;boardBanner&quot;&gt;
        ///      &lt;div class=&quot;boardTitle&quot;&gt;
        ///        ChanArchiver
        ///      &lt;/div&gt;
        ///      &lt;div class=&quot;boardSubtitle&quot;&gt;
        ///        C#.NET 4chan archiver
        ///      &lt;/div&gt;
        ///    &lt;/div&gt;
        ///    
        ///    &lt;div id=&quot;top&quot;&gt;&lt;/div&gt;
        ///
        ///    &lt;br /&gt;
        ///
        ///    &lt;div class=&quot;desktop&quot;&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string full_page {
            get {
                return ResourceManager.GetString("full_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hr {
            get {
                object obj = ResourceManager.GetObject("hr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;file&quot; id=&quot;f{file:id}&quot;&gt;
        ///    &lt;div class=&quot;fileInfo desktop&quot;&gt;
        ///        &lt;span class=&quot;fileText&quot; id=&quot;fT{file:id}&quot;&gt;
        ///        &lt;a class=&quot;fn&quot; href=&quot;{file:link}&quot;&gt;{file:name}&lt;/a&gt; - ({file:size}, {file:dimensions})&lt;/span&gt;
        ///    &lt;/div&gt;
        ///    &lt;a class=&quot;fileThumb&quot; href=&quot;{file:link}&quot; target=&quot;_blank&quot;&gt;
        ///        &lt;img src=&quot;{file:thumblink}&quot; alt=&quot;{file:name}&quot;/&gt;
        ///    &lt;/a&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string image_file {
            get {
                return ResourceManager.GetString("image_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.0 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k=&quot;&quot;.trim,l={},m=&quot;1.11.0&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_js {
            get {
                return ResourceManager.GetString("jquery_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html
        ///{
        ///    -webkit-text-size-adjust: 100%;
        ///}
        ///
        ///body
        ///{
        ///    margin-left: 0;
        ///    margin-right: 0;
        ///    margin-top: 5px;
        ///    padding-left: 15px;
        ///    padding-right: 15px;
        ///}
        ///
        ///.mobile, .mobileinline, .mobileib
        ///{
        ///    display: none !important;
        ///}
        ///
        ///div#footer
        ///{
        ///    clear: both;
        ///    text-align: center;
        ///}
        ///
        ///hr
        ///{
        ///    background: url(&quot;../res/hr.png&quot;) repeat-x scroll 0px 0px transparent;
        ///    border: 0px none;
        ///    color: rgb(204, 204, 204);
        ///    height: 4px;
        ///    padding: 0px;
        ///    clear: both;
        ///}        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layout {
            get {
                return ResourceManager.GetString("layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] locked {
            get {
                object obj = ResourceManager.GetObject("locked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot;&gt;
        ///
        ///    &lt;title&gt;ChanARCHIVER&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    &lt;link href=&quot;/res/bootstrap.css&quot; re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logs_page {
            get {
                return ResourceManager.GetString("logs_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;opContainer&quot; id=&quot;pc{wpost:id}&quot;&gt;
        ///
        ///  &lt;div id=&quot;p{wpost:id}&quot; class=&quot;post op&quot;&gt;
        ///    {wpost:file}
        ///
        ///    &lt;div class=&quot;postInfo desktop&quot;&gt;
        ///      {wpost:subject}
        ///      &lt;span class=&quot;name&quot;&gt;{wpost:name}&lt;/span&gt;
        ///      {wpost:posterId}
        ///      &lt;span class=&quot;dateTime&quot;&gt;{wpost:time}&lt;/span&gt;
        ///
        ///      &lt;span class=&quot;postNum&quot;&gt;
        ///        &lt;a href=&quot;{postLink}&quot;&gt;No.&lt;/a&gt;
        ///
        ///        &lt;a href=&quot;#p{wpost:id}&quot; title=&quot;{wpost:id}&quot;&gt;{wpost:id}&lt;/a&gt;
        ///      &lt;/span&gt;
        ///      {op:replycount} {op:sticky} {op:locked}
        ///    &lt;/div&gt;
        ///    {wpost:c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string op_post {
            get {
                return ResourceManager.GetString("op_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;replyContainer&quot; id=&quot;pc{wpost:id}&quot;&gt;
        ///
        ///  &lt;div id=&quot;p{wpost:id}&quot; class=&quot;post reply&quot;&gt;
        ///
        ///    &lt;div class=&quot;postInfo desktop&quot;&gt;
        ///
        ///      {wpost:subject}
        ///      &lt;span class=&quot;name&quot;&gt;{wpost:name}&lt;/span&gt;
        ///      {wpost:posterId}
        ///      &lt;span class=&quot;dateTime&quot;&gt;{wpost:time}&lt;/span&gt;
        ///
        ///      &lt;span class=&quot;postNum&quot;&gt;
        ///        &lt;a href=&quot;#{wpost:id}&quot;&gt;No.&lt;/a&gt;
        ///        &lt;a href=&quot;#p{wpost:id}&quot; title=&quot;{wpost:id}&quot;&gt;{wpost:id}&lt;/a&gt;
        ///      &lt;/span&gt;
        ///
        ///    &lt;/div&gt;
        ///
        ///    {wpost:file}
        ///
        ///    {wpost:comment}
        ///  &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string reply_post {
            get {
                return ResourceManager.GetString("reply_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sticky {
            get {
                object obj = ResourceManager.GetObject("sticky", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;thread&quot; id=&quot;t{id}&quot;&gt;
        ///    {Content}
        ///&lt;/div&gt;&lt;hr /&gt;.
        /// </summary>
        internal static string thread {
            get {
                return ResourceManager.GetString("thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;/&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;&quot;/&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;/res/favicon.ico&quot;/&gt;
        ///
        ///    &lt;title&gt;[ChanArchiver] - Watch Jobs&lt;/title&gt;
        ///
        ///    &lt;!-- Bootstrap core CSS --&gt;
        ///    &lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wjobs_page {
            get {
                return ResourceManager.GetString("wjobs_page", resourceCulture);
            }
        }
    }
}
